LSSDDistanceEdReg/LSSDDistanceEdReg.WebFrontEnd/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace LSSDDistanceEdReg.WebFrontEnd.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

LSSDDistanceEdReg/LSSDDistanceEdReg.WebFrontEnd/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using LSSD.DistanceEdReg;
using LSSD.DistanceEdReg.Data;
using LSSD.DistanceEdReg.Util;
using LSSDDistanceEdReg.WebFrontEnd.Services;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;

namespace LSSDDistanceEdReg.WebFrontEnd.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        public List<string> regErrors = new List<string>();

        private DistanceEdRequestService _requestService;
        private DistanceEdClassService _classService;

        public IndexModel(DistanceEdRequestService requestService, DistanceEdClassService classService, ILogger<IndexModel> logger)
        {
            this._requestService = requestService;
            this._classService = classService;
            _logger = logger;
        }

        public void OnGet()
        {

        }

        public IActionResult OnPostFormSubmit()
        {
            if (ModelState.IsValid)
            {
                regErrors.Clear();

                string studentName = Request.Form["txtStudentName"].ToString();
                string studentNumber = Request.Form["txtStudentNumber"].ToString();
                string studentSchool = Request.Form["txtStudentSchool"].ToString();
                string comments = Request.Form["txtNotes"].ToString();
                string requestor = Request.Form["txtRequestor"].ToString();

                string mentorName = Request.Form["txtMentor"].ToString() ?? string.Empty;
                int courseID = Parsers.ToInt(Request.Form["txtCourseID"].ToString() ?? string.Empty);

                // Find checked classes
                // The easy way to do this would be check all submitted form elements for anything that starts with "chkClass_"
                // The safe way to do this would be to load all valid classes, and compare to that list instead

                Dictionary<int, DistanceEdClass> availableClasses = _classService.GetAllAvailable(DateTime.Now).ToDictionary(x => x.ID);
                
                DistanceEdRequest newRequest = new DistanceEdRequest()
                {
                    StudentName = studentName,
                    StudentNumber = studentNumber,
                    StudentBaseSchool = studentSchool,
                    Comments = comments,
                    CourseID = courseID,
                    MentorTeacherName = mentorName,
                    Requestor = requestor
                };
                               
                
                // Validate
                
                if (courseID > 0) {                     
                    DistanceEdClass selectedClass = availableClasses[courseID] ?? null;
                    if (selectedClass == null)
                    {
                        regErrors.Add("Course with ID \"" + courseID + "\" was not found.");
                    }
                    else
                    {
                        if (selectedClass.MentorTeacherRequired)
                        {
                            if (string.IsNullOrEmpty(mentorName))
                            {
                                regErrors.Add("The class \"" + selectedClass.Name + "\" requires a mentor teacher, but no name was provided.");
                            }
                        }
                    }
                } else
                {
                    regErrors.Add("No course selected");
                }

                if (string.IsNullOrEmpty(studentName)) { regErrors.Add("Student name is required"); }
                if (string.IsNullOrEmpty(studentNumber)) { regErrors.Add("Student number is required"); }
                if (string.IsNullOrEmpty(studentSchool)) { regErrors.Add("Student base school is required"); }
                if (string.IsNullOrEmpty(requestor)) { regErrors.Add("Requestor name is required"); }


                // Submit to DB
                if (regErrors.Count == 0)
                {
                    try
                    {
                        _requestService.Add(newRequest);
                    }
                    catch (Exception ex)
                    {
                        regErrors.Add(ex.Message);
                    }
                }

                if (regErrors.Count == 0)
                {
                    return RedirectToPage("Thanks");
                }
                else
                {
                    return Page();
                }
            } else
            {
                return Page();
            }
        }
    }
}

LSSDDistanceEdReg/LSSDDistanceEdReg.WebFrontEnd/Pages/thanks.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace LSSDDistanceEdReg.WebFrontEnd
{
    public class thanksModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

LSSDDistanceEdReg/LSSDDistanceEdReg.WebFrontEnd/Pages/Index.cshtml
@page "{Id=0}"
@using LSSD.DistanceEdReg
@using LSSD.DistanceEdReg.Data
@using LSSD.DistanceEdReg.Util
@using Microsoft.Extensions.Configuration;
@inject LSSDDistanceEdReg.WebFrontEnd.Services.DistanceEdClassService distanceEdClassService
@model IndexModel
@{
    ViewData["Title"] = "Register";

    // Create a list of courses to use later
    List<DistanceEdClass> availableClasses = distanceEdClassService.GetAllAvailable(DateTime.Now);

    DistanceEdClass displayedClass = null;

    // Check if we've been given a course number
    bool validCourseSelected = false;

    string courseIdString = RouteData.Values["Id"].ToString() ?? string.Empty;

    if (!string.IsNullOrEmpty(courseIdString))
    {
        int courseIdParsed = courseIdString.ToInt();
        DistanceEdClass selectedClass = distanceEdClassService.Get(courseIdParsed);
        if (selectedClass != null)
        {
            validCourseSelected = true;
            displayedClass = selectedClass;
        }
    }

}
<img src="Images/LSSDVirtLogo.png" />
@if ((!validCourseSelected))
{
    <h2>To begin, please select a course:</h2>
    <ul>
        @foreach (DistanceEdClass dec in availableClasses.OrderBy(x => x.Name))
        {
            <li><a href="/@dec.ID">@dec.Name</a></li>

        }
    </ul>
}
else if (displayedClass != null)
{
    <h1>Register a student in an LSSD Virtual course</h1>
    <ul>
        <li>Once submitted, this form is processed by Division Office staff.</li>
        <li>You will receive an email when the registration has been complete.</li>
        <li>Registration may take several business days to complete.</li>
    </ul>
    <br />
    @foreach (string errmsg in Model.regErrors)
    {
        <div class="alert alert-danger">
            <strong>Error:</strong> @errmsg
        </div>
    }
    <br />
    <form method="post" asp-page-handler="FormSubmit" style="display: inline;">
        <input name="txtCourseID" type="hidden" value="@displayedClass.ID" />
        <table border="0" cellpadding="5" cellspacing="5">
            <tr>
                <td valign="top"><b>Your Name</b></td>
                <td valign="top"><input name="txtRequestor" class="form-control" type="text" style="width: 500px;" placeholder="Alfred Pennyworth" required></td>
            </tr>
            <tr>
                <td valign="top"><b>Student Name</b></td>
                <td valign="top"><input name="txtStudentName" class="form-control" type="text" style="width: 500px;" placeholder="Bruce Wayne" required></td>
            </tr>
            <tr>
                <td valign="top"><b>Student Number</b></td>
                <td valign="top"><input name="txtStudentNumber" class="form-control" type="text" style="width: 500px;" placeholder="123456789" required></td>
            </tr>
            <tr>
                <td valign="top"><b>Student Base School</b></td>
                <td valign="top"><input name="txtStudentSchool" class="form-control" type="text" style="width: 500px;" placeholder="Miskatonic High School" required></td>
            </tr>
            <tr>
                <td valign="top"><b>Additional Notes</b></td>
                <td valign="top"><textarea name="txtNotes" class="form-control"></textarea></td>
            </tr>

            <tr>
                <td valign="top"><b>Course</b></td>
                <td valign="top">
                    <b>@displayedClass.Name</b><br />
                    <div style="padding-left: 10px; font-size: 75%">
                        <b>Course starts: </b>@displayedClass.Starts.ToLongDateString()<br />
                        <b>Course ends: </b>@displayedClass.Ends.ToLongDateString()<br />
                    </div>
                    @if (!string.IsNullOrEmpty(displayedClass.Description))
                    {
                        <br />
                        <div style="font-size: 75%;">
                            @displayedClass.Description
                        </div>
                    }
                    @if (!string.IsNullOrEmpty(displayedClass.MoreInfoURL))
                    {
                        <div style="display: inline; font-size: 90%;"><a href="@displayedClass.MoreInfoURL">Click here for more information about this course</a></div>
                    }

                </td>
            </tr>

            @if (displayedClass.MentorTeacherRequired)
            {
                <tr>
                    <td valign="top">
                        <b>Mentor Teacher</b><br />
                        <div style="font-size: 75%; max-width: 300px;">A <b>Mentor Teacher</b> is required for registration into this course. Mentor teachers are teachers at the student's <i>base</i> school who this student can go to for help.</div>
                    </td>
                    <td valign="top">
                        <input name="txtMentor" type="text" class="form-control" style="width: 500px;" placeholder="Mentor Teacher Name" required />
                    </td>
                </tr>
            }

            <tr>
                <td valign="top">&nbsp;</td>
                <td cospan="1" align="center" valign="top">
                    <button class="btn btn-primary large" style="margin-left: 10px;">Submit Registration</button>
                </td>
            </tr>
        </table>
    </form>
}

LSSDDistanceEdReg/LSSDDistanceEdReg.WebFrontEnd/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LSSDVirtual Registration</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
</head>
<body>    
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - Living Sky School Division No. 202 - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    @RenderSection("Scripts", required: false)
</body>
</html>

LSSDDistanceEdReg/LSSDDistanceEdReg.WebFrontEnd/Pages/thanks.cshtml
@page "/Thanks"
@model LSSDDistanceEdReg.WebFrontEnd.thanksModel
@{
    ViewData["Title"] = "thanks";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<h1>Registration Submitted</h1>
<ul>
    <li>Division Office staff will now complete the enrolment based on the information you provided.</li>
    <li>It may take several business days to complete the enrolment.</li>
    <li>You will receive an email when the registration has been complete.</li>
</ul>
<br/><br/>
<a href="/">Click here to go back to the course list.</a>